packages:
  - apps/*
  - packages/*
catalog:
  hono: ^4.8.2
  "@orpc/server": ^1.10.0
  "@orpc/openapi": ^1.10.0
  "@orpc/zod": ^1.10.0
  better-auth: ^1.4.0
  ai: ^5.0.49
  "@ai-sdk/google": ^2.0.13
  dotenv: ^17.2.2
  alchemy: ^0.77.0
  "@orpc/client": ^1.10.0
  "@libsql/client": ^0.14.0
  libsql: ^0.5.22
  drizzle-orm: ^0.44.2
