packages:
  - apps/*
  - packages/*
catalog:
  hono: ^4.10.6
  '@orpc/server': ^1.11.3
  '@orpc/openapi': ^1.11.3
  '@orpc/zod': ^1.11.3
  better-auth: ^1.4.0
  ai: ^5.0.101
  '@ai-sdk/google': ^2.0.43
  dotenv: ^17.2.3
  alchemy: ^0.78.0
  '@orpc/client': ^1.10.0
  '@libsql/client': ^0.15.15
  libsql: ^0.5.22
  drizzle-orm: ^0.44.7
onlyBuiltDependencies:
  - esbuild
  - sharp
  - workerd
